config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :notes
  resources :fb_users
  resources :tickets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


    root  'pages#home'
    get 'setting', to: 'pages#edit'

    
end

app/models/fb_user.rb
class FbUser < ApplicationRecord
    before_save { self.email = email.downcase}

    validates :name, presence: true,
                    uniqueness: {case_sensitive: false},
                    length: {minimum: 3, maximum: 25}

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, presence: true,
                        uniqueness: {case_sensitive: false},
                        format: { with: VALID_EMAIL_REGEX}
                        
    has_secure_password
    
end

app/controllers/fb_users_controller.rb
class FbUsersController < ApplicationController
  include FbUsersHelper
  include ApplicationHelper
  
  before_action :set_fb_user, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  # GET /fb_users
  # GET /fb_users.json
  def index
    @fb_users = FbUser.all
  end

  # GET /fb_users/1
  # GET /fb_users/1.json
  def show
  end

  # GET /fb_users/new
  def new
    @fb_user = FbUser.new
  end

  # GET /fb_users/1/edit
  def edit
  end

  # POST /fb_users
  # POST /fb_users.json
  def create
    @fb_user = FbUser.new(fb_user_params)

    respond_to do |format|
      if @fb_user.save
        format.html { redirect_to @fb_user, notice: 'Fb user was successfully created.' }
        format.json { render :show, status: :created, location: @fb_user }
      else
        format.html { render :new }
        format.json { render json: @fb_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fb_users/1
  # PATCH/PUT /fb_users/1.json
  def update
    @fb_user = FbUser.find(params[:id])
    respond_to do |format|
      if @fb_user.update(fb_user_params)
        format.html { redirect_to @fb_user, notice: 'Fb user was successfully updated.' }
        format.json { render :show, status: :ok, location: @fb_user }
      else
        format.html { render :edit }
        format.json { render json: @fb_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fb_users/1
  # DELETE /fb_users/1.json
  def destroy
    @fb_user.destroy
    session[:fb_user_id] = nil if @fb_user == current_user
    respond_to do |format|
      format.html { redirect_to fb_users_url, notice: 'Fb user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fb_user
      @fb_user = FbUser.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fb_user_params
      params.require(:fb_user).permit(:link, :name, :email, :password, :phone)
    end
    
    def require_same_user
      if current_user != @fb_user && !current_user.try(:admin?)
        flash[:alert] = "You can only edit your own account"
        redirect_to @fb_user
      end
    end
end

app/helpers/fb_users_helper.rb
module FbUsersHelper
    
end

app/views/fb_users/_form.html.erb
<%= form_with(model: fb_user, local: true) do |form| %>
  <% if fb_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fb_user.errors.count, "error") %> prohibited this fb_user from being saved:</h2>

      <ul>
        <% fb_user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

 
  <div class="field">
  <%= form.label :email %>
  <%= form.email_field :email %>
</div>

<div class="field">
<%= form.label :phone %>
<%= form.text_field :phone %>
</div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit(@fb_user.new_record? ? "Sign Up" : "Update Account" ) %>
  </div>
<% end %>

app/views/fb_users/edit.html.erb
<h1>Editing Your Account</h1>

<%= render 'form', fb_user: @fb_user %>

<%= link_to 'Show', @fb_user %> |
<%= link_to 'Log Out' , logout_path%>

app/views/fb_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Control Panel </h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @fb_users.each do |fb_user| %>
      <% if !fb_user.admin? %>
        <tr>
          <td><%= fb_user.link %></td>
          <td><%= fb_user.name %></td>
          <td><%= fb_user.email %></td>
          <td><%= fb_user.phone %></td>

          <td><%= link_to 'Show', fb_user %></td>
          <td><%= link_to 'Edit', edit_fb_user_path(fb_user) %></td>
          <td><%= link_to 'Destroy', fb_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Log Out', logout_path %>

app/views/fb_users/new.html.erb
<h1>Create New Fb User</h1>

<%= render 'form', fb_user: @fb_user %>

<%= link_to 'Home Page', root_path %>

app/views/fb_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fb_user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>



<%= link_to 'Edit', edit_fb_user_path(@fb_user) %> |
<%= link_to 'Back', fb_users_path %>